<a href="https://colab.research.google.com/github/suhrudsharma/Adaptive-MNN-IoT23/blob/main/AMNN_2ndDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================
# FIND ALL CSV FILES IN YOUR GOOGLE DRIVE
# ============================================

import os

for root, dirs, files in os.walk("/content/drive"):
    for f in files:
        if f.endswith(".csv"):
            print(os.path.join(root, f))


/content/drive/MyDrive/CICIOT23/train/train.csv
/content/drive/MyDrive/CICIOT23/test/test.csv
/content/drive/MyDrive/CICIOT23/validation/validation.csv


In [3]:
# ============================================
# CELL 1 — Mount Drive & Load CICIoT23 CSVs
# ============================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_path = "/content/drive/MyDrive/CICIOT23/train/train.csv"
test_path  = "/content/drive/MyDrive/CICIOT23/test/test.csv"
val_path   = "/content/drive/MyDrive/CICIOT23/validation/validation.csv"

df_train = pd.read_csv(train_path)
df_test  = pd.read_csv(test_path)
df_val   = pd.read_csv(val_path)

print("Train shape:", df_train.shape)
print("Test shape:", df_test.shape)
print("Validation shape:", df_val.shape)

df_train.head()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Train shape: (5491971, 47)
Test shape: (1176851, 47)
Validation shape: (1176851, 47)


flow_duration  Header_Length  Protocol Type  Duration       Rate  \
0       0.000000         757.00           6.00     64.00  23.671858   
1       0.000000          54.00           6.00     64.00   2.393046   
2       0.033982          56.78           6.11     64.64   1.192715   
3       0.000000           0.00          47.00     64.00   9.841972   
4       3.944828         108.00           6.00     64.00   0.506993   

       Srate  Drate  fin_flag_number  syn_flag_number  rst_flag_number  ...  \
0  23.671858    0.0              0.0              0.0              0.0  ...   
1   2.393046    0.0              0.0              1.0              0.0  ...   
2   1.192715    0.0              0.0              0.0              0.0  ...   
3   9.841972    0.0              0.0              0.0              0.0  ...   
4   0.506993    0.0              0.0              1.0              0.0  ...   

          Std  Tot size           IAT  Number   Magnitue      Radius  \
0  538.470740    944.00  8.334058e+07     9.5  41.845546  761.456760   
1    0.000000     54.00  8.309327e+07     9.5  10.392305    0.000000   
2    1.727526     54.29  8.333086e+07     9.5  10.462813    2.445286   
3    0.000000    592.00  8.370278e+07     9.5  34.409301    0.000000   
4    0.000000     54.00  8.297270e+07     9.5  10.392305    0.000000   

      Covariance  Variance  Weight                   label  
0  305219.322301      0.95  141.55  DDoS-ACK_Fragmentation  
1       0.000000      0.00  141.55          DDoS-SYN_Flood  
2      16.853118      0.19  141.55       DDoS-PSHACK_Flood  
3       0.000000      0.00  141.55      Mirai-greeth_flood  
4       0.000000      0.00  141.55           DoS-SYN_Flood  

[5 rows x 47 columns]

In [4]:
# ============================================
# CELL 2 — Combine train, test, validation
# ============================================

df_train['split'] = 'train'
df_test['split'] = 'test'
df_val['split'] = 'val'

df = pd.concat([df_train, df_test, df_val], ignore_index=True)
print("Combined shape:", df.shape)

df.head()


Combined shape: (7845673, 48)


flow_duration  Header_Length  Protocol Type  Duration       Rate  \
0       0.000000         757.00           6.00     64.00  23.671858   
1       0.000000          54.00           6.00     64.00   2.393046   
2       0.033982          56.78           6.11     64.64   1.192715   
3       0.000000           0.00          47.00     64.00   9.841972   
4       3.944828         108.00           6.00     64.00   0.506993   

       Srate  Drate  fin_flag_number  syn_flag_number  rst_flag_number  ...  \
0  23.671858    0.0              0.0              0.0              0.0  ...   
1   2.393046    0.0              0.0              1.0              0.0  ...   
2   1.192715    0.0              0.0              0.0              0.0  ...   
3   9.841972    0.0              0.0              0.0              0.0  ...   
4   0.506993    0.0              0.0              1.0              0.0  ...   

   Tot size           IAT  Number   Magnitue      Radius     Covariance  \
0    944.00  8.334058e+07     9.5  41.845546  761.456760  305219.322301   
1     54.00  8.309327e+07     9.5  10.392305    0.000000       0.000000   
2     54.29  8.333086e+07     9.5  10.462813    2.445286      16.853118   
3    592.00  8.370278e+07     9.5  34.409301    0.000000       0.000000   
4     54.00  8.297270e+07     9.5  10.392305    0.000000       0.000000   

   Variance  Weight                   label  split  
0      0.95  141.55  DDoS-ACK_Fragmentation  train  
1      0.00  141.55          DDoS-SYN_Flood  train  
2      0.19  141.55       DDoS-PSHACK_Flood  train  
3      0.00  141.55      Mirai-greeth_flood  train  
4      0.00  141.55           DoS-SYN_Flood  train  

[5 rows x 48 columns]

In [5]:
df["label"].value_counts().head(20)


label
DDoS-ICMP_Flood            1210546
DDoS-UDP_Flood              910741
DDoS-TCP_Flood              756122
DDoS-PSHACK_Flood           687565
DDoS-SYN_Flood              683505
DDoS-RSTFINFlood            678823
DDoS-SynonymousIP_Flood     603358
DoS-UDP_Flood               557495
DoS-TCP_Flood               448927
DoS-SYN_Flood               339804
BenignTraffic               184766
Mirai-greeth_flood          165977
Mirai-udpplain              149664
Mirai-greip_flood           126967
DDoS-ICMP_Fragmentation      75878
MITM-ArpSpoofing             51897
DDoS-UDP_Fragmentation       48614
DDoS-ACK_Fragmentation       48067
DNS_Spoofing                 30349
Recon-HostDiscovery          22550
Name: count, dtype: int64

In [6]:
# ============================================
# CELL 3 — Safe mapping without merging big dataframes
# ============================================

def map_to_three_classes(label):
    label = str(label).lower()

    if "benign" in label:
        return "Benign"
    if ("recon" in label or "scan" in label or
        "host" in label or "discovery" in label or
        "probe" in label):
        return "Scan"
    return "C&C"

# Apply per split (RAM-safe)
df_train["class"] = df_train["label"].apply(map_to_three_classes)
df_test["class"] = df_test["label"].apply(map_to_three_classes)
df_val["class"] = df_val["label"].apply(map_to_three_classes)

print("Train class distribution:\n", df_train["class"].value_counts())
print("\nTest class distribution:\n", df_test["class"].value_counts())
print("\nValidation class distribution:\n", df_val["class"].value_counts())


Train class distribution:
 class
C&C       5320816
Benign     129538
Scan        41617
Name: count, dtype: int64

Test class distribution:
 class
C&C       1140330
Benign      27709
Scan         8812
Name: count, dtype: int64

Validation class distribution:
 class
C&C       1140317
Benign      27519
Scan         9015
Name: count, dtype: int64


In [7]:
# ============================================
# CELL 4 — Identify feature columns safely
# ============================================

# columns we must exclude
non_feature_cols = ["label", "class"]

feature_cols = [c for c in df_train.columns if c not in non_feature_cols]

print("Total features:", len(feature_cols))
print("First 10 features:", feature_cols[:10])


Total features: 47
First 10 features: ['flow_duration', 'Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number']


In [8]:
# ============================================
# CELL 5 — STRATIFIED SAMPLING (RAM-SAFE)
# ============================================

import math
import numpy as np

# Desired sample sizes (change if you want larger/smaller)
SAMPLE_TRAIN = 200_000
SAMPLE_TEST  = 50_000
SAMPLE_VAL   = 50_000

def stratified_sample(df_split, target_col, desired_n):
    counts = df_split[target_col].value_counts()
    total = counts.sum()
    # desired per class proportional to original distribution
    desired_per_class = (counts / total * desired_n).round().astype(int).to_dict()
    # ensure at least 1 per class if available
    sampled_parts = []
    for cls, want in desired_per_class.items():
        avail = len(df_split[df_split[target_col] == cls])
        take = min(avail, want)
        if take <= 0:
            continue
        sampled_parts.append(df_split[df_split[target_col] == cls].sample(n=take, random_state=42))
    sampled = pd.concat(sampled_parts, ignore_index=True)
    # if rounding made total smaller/larger, fix by sampling or trimming random
    if len(sampled) < desired_n:
        need = desired_n - len(sampled)
        # sample additional rows from df_split (any class) without replacement
        extra = df_split.drop(sampled.index, errors='ignore').sample(n=min(need, len(df_split)-len(sampled)), random_state=42)
        sampled = pd.concat([sampled, extra], ignore_index=True)
    if len(sampled) > desired_n:
        sampled = sampled.sample(n=desired_n, random_state=42).reset_index(drop=True)
    return sampled.reset_index(drop=True)

print("Sampling train ...")
df_train_s = stratified_sample(df_train, "class", SAMPLE_TRAIN)
print("Sampling test ...")
df_test_s  = stratified_sample(df_test,  "class", SAMPLE_TEST)
print("Sampling val ...")
df_val_s   = stratified_sample(df_val,   "class", SAMPLE_VAL)

print("\nSampled shapes:")
print("df_train_s:", df_train_s.shape)
print("df_test_s :", df_test_s.shape)
print("df_val_s  :", df_val_s.shape)

print("\nClass distribution in sampled train:")
print(df_train_s["class"].value_counts())
print("\nSampled test class distribution:")
print(df_test_s["class"].value_counts())
print("\nSampled val class distribution:")
print(df_val_s["class"].value_counts())


Sampling train ...
Sampling test ...
Sampling val ...

Sampled shapes:
df_train_s: (200000, 49)
df_test_s : (50000, 49)
df_val_s  : (50000, 49)

Class distribution in sampled train:
class
C&C       193767
Benign      4717
Scan        1516
Name: count, dtype: int64

Sampled test class distribution:
class
C&C       48449
Benign     1177
Scan        374
Name: count, dtype: int64

Sampled val class distribution:
class
C&C       48448
Benign     1169
Scan        383
Name: count, dtype: int64


In [9]:
# ============================================
# CELL 6 — Encode labels (Benign=0, Scan=1, C&C=2)
# ============================================

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(df_train_s["class"])
y_test  = le.transform(df_test_s["class"])
y_val   = le.transform(df_val_s["class"])

print("Classes:", le.classes_)
print("Encoded as:", list(le.transform(le.classes_)))


Classes: ['Benign' 'C&C' 'Scan']
Encoded as: [np.int64(0), np.int64(1), np.int64(2)]


In [10]:
# ============================================
# CELL 7 — Build X matrices (RAM-safe)
# ============================================

X_train = df_train_s[feature_cols].values
X_test  = df_test_s[feature_cols].values
X_val   = df_val_s[feature_cols].values

print("Train X:", X_train.shape)
print("Test X:", X_test.shape)
print("Val X:", X_val.shape)


Train X: (200000, 47)
Test X: (50000, 47)
Val X: (50000, 47)


In [11]:
# ============================================
# CELL 8 — Scale features
# ============================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)
X_val_scaled   = scaler.transform(X_val)

print("Scaling complete.")


ValueError: could not convert string to float: 'train'

In [1]:
# ============================================
# CELL 1 — Mount Drive & Load CICIoT23 CSVs
# ============================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_path = "/content/drive/MyDrive/CICIOT23/train/train.csv"
test_path  = "/content/drive/MyDrive/CICIOT23/test/test.csv"
val_path   = "/content/drive/MyDrive/CICIOT23/validation/validation.csv"

df_train = pd.read_csv(train_path)
df_test  = pd.read_csv(test_path)
df_val   = pd.read_csv(val_path)

print("Train:", df_train.shape)
print("Test :", df_test.shape)
print("Val  :", df_val.shape)

df_train.head()


Mounted at /content/drive
Train: (5491971, 47)
Test : (1176851, 47)
Val  : (1176851, 47)


flow_duration  Header_Length  Protocol Type  Duration       Rate  \
0       0.000000         757.00           6.00     64.00  23.671858   
1       0.000000          54.00           6.00     64.00   2.393046   
2       0.033982          56.78           6.11     64.64   1.192715   
3       0.000000           0.00          47.00     64.00   9.841972   
4       3.944828         108.00           6.00     64.00   0.506993   

       Srate  Drate  fin_flag_number  syn_flag_number  rst_flag_number  ...  \
0  23.671858    0.0              0.0              0.0              0.0  ...   
1   2.393046    0.0              0.0              1.0              0.0  ...   
2   1.192715    0.0              0.0              0.0              0.0  ...   
3   9.841972    0.0              0.0              0.0              0.0  ...   
4   0.506993    0.0              0.0              1.0              0.0  ...   

          Std  Tot size           IAT  Number   Magnitue      Radius  \
0  538.470740    944.00  8.334058e+07     9.5  41.845546  761.456760   
1    0.000000     54.00  8.309327e+07     9.5  10.392305    0.000000   
2    1.727526     54.29  8.333086e+07     9.5  10.462813    2.445286   
3    0.000000    592.00  8.370278e+07     9.5  34.409301    0.000000   
4    0.000000     54.00  8.297270e+07     9.5  10.392305    0.000000   

      Covariance  Variance  Weight                   label  
0  305219.322301      0.95  141.55  DDoS-ACK_Fragmentation  
1       0.000000      0.00  141.55          DDoS-SYN_Flood  
2      16.853118      0.19  141.55       DDoS-PSHACK_Flood  
3       0.000000      0.00  141.55      Mirai-greeth_flood  
4       0.000000      0.00  141.55           DoS-SYN_Flood  

[5 rows x 47 columns]

In [2]:
# ============================================
# CELL 2 — Map labels to 3 classes (RAM-safe)
# ============================================

def map_to_three_classes(label):
    label = str(label).lower()

    # Benign
    if "benign" in label:
        return "Benign"

    # Scan / Reconnaissance
    if ("recon" in label or
        "scan" in label or
        "host" in label or
        "discovery" in label or
        "probe" in label):
        return "Scan"

    # Everything else = C&C / Botnet attack
    return "C&C"


df_train["class"] = df_train["label"].apply(map_to_three_classes)
df_test["class"]  = df_test["label"].apply(map_to_three_classes)
df_val["class"]   = df_val["label"].apply(map_to_three_classes)

print("\nTRAIN CLASS DISTRIBUTION:\n", df_train["class"].value_counts())
print("\nTEST CLASS DISTRIBUTION:\n", df_test["class"].value_counts())
print("\nVAL CLASS DISTRIBUTION:\n", df_val["class"].value_counts())



TRAIN CLASS DISTRIBUTION:
 class
C&C       5320816
Benign     129538
Scan        41617
Name: count, dtype: int64

TEST CLASS DISTRIBUTION:
 class
C&C       1140330
Benign      27709
Scan         8812
Name: count, dtype: int64

VAL CLASS DISTRIBUTION:
 class
C&C       1140317
Benign      27519
Scan         9015
Name: count, dtype: int64


In [3]:
# ============================================
# CELL 3 — STRATIFIED SAMPLING (RAM-SAFE)
# ============================================

import pandas as pd

def stratified_sample(df_split, target_col, desired_n):
    counts = df_split[target_col].value_counts()
    total = counts.sum()

    # proportional sampling
    desired_per_class = (counts / total * desired_n).round().astype(int).to_dict()

    sampled_parts = []
    for cls, want in desired_per_class.items():
        available = df_split[df_split[target_col] == cls]
        take = min(len(available), want)
        if take > 0:
            sampled_parts.append(available.sample(n=take, random_state=42))

    sampled = pd.concat(sampled_parts, ignore_index=True)

    # final adjust if slightly off
    if len(sampled) > desired_n:
        sampled = sampled.sample(n=desired_n, random_state=42)
    elif len(sampled) < desired_n:
        extra = df_split.drop(sampled.index, errors='ignore').sample(
            n=desired_n - len(sampled), random_state=42
        )
        sampled = pd.concat([sampled, extra], ignore_index=True)

    return sampled.reset_index(drop=True)

# desired sample sizes
TRAIN_N = 200_000
TEST_N  = 50_000
VAL_N   = 50_000

print("Sampling train...")
df_train_s = stratified_sample(df_train, "class", TRAIN_N)

print("Sampling test...")
df_test_s  = stratified_sample(df_test, "class", TEST_N)

print("Sampling val...")
df_val_s   = stratified_sample(df_val, "class", VAL_N)

print("\nSampled shapes:")
print("Train:", df_train_s.shape)
print("Test :", df_test_s.shape)
print("Val  :", df_val_s.shape)

print("\nSampled TRAIN class distribution:")
print(df_train_s["class"].value_counts())

print("\nSampled TEST class distribution:")
print(df_test_s["class"].value_counts())

print("\nSampled VAL class distribution:")
print(df_val_s["class"].value_counts())


Sampling train...
Sampling test...
Sampling val...

Sampled shapes:
Train: (200000, 48)
Test : (50000, 48)
Val  : (50000, 48)

Sampled TRAIN class distribution:
class
C&C       193767
Benign      4717
Scan        1516
Name: count, dtype: int64

Sampled TEST class distribution:
class
C&C       48449
Benign     1177
Scan        374
Name: count, dtype: int64

Sampled VAL class distribution:
class
C&C       48448
Benign     1169
Scan        383
Name: count, dtype: int64


In [4]:
# ============================================
# CELL 4 — Detect and keep numeric features (safe)
# ============================================

import numpy as np
import pandas as pd

# Identify all columns except labels
reserved = {"label", "class"}
feature_cols = [c for c in df_train_s.columns if c not in reserved]

print("Initial feature columns:", len(feature_cols))

numeric_ok = {}

# Check numeric fraction for each column using TRAIN data
for c in feature_cols:
    coerced = pd.to_numeric(df_train_s[c], errors="coerce")
    frac_numeric = coerced.notna().sum() / len(coerced)
    numeric_ok[c] = frac_numeric

# Columns kept = ≥ 90% numeric
THRESHOLD = 0.90
final_numeric_cols = [c for c, frac in numeric_ok.items() if frac >= THRESHOLD]
non_numeric_cols   = [c for c, frac in numeric_ok.items() if frac < THRESHOLD]

print("\nNon-numeric columns removed:")
for c in non_numeric_cols:
    print(f" - {c} (numeric fraction={numeric_ok[c]:.3f})")

print("\nFinal numeric feature count:", len(final_numeric_cols))
print("Final numeric feature names:", final_numeric_cols[:15])  # first 15

# Convert numeric columns to float explicitly
for c in final_numeric_cols:
    df_train_s[c] = pd.to_numeric(df_train_s[c], errors="coerce")
    df_test_s[c]  = pd.to_numeric(df_test_s[c], errors="coerce")
    df_val_s[c]   = pd.to_numeric(df_val_s[c], errors="coerce")

print("\nNumeric conversion complete.")


Initial feature columns: 46

Non-numeric columns removed:

Final numeric feature count: 46
Final numeric feature names: ['flow_duration', 'Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count']

Numeric conversion complete.


In [5]:
# ============================================
# CELL 5 — Build X & y Matrices (RAM-safe)
# ============================================

import numpy as np

# X matrices (numeric only)
X_train = df_train_s[final_numeric_cols].values
X_test  = df_test_s[final_numeric_cols].values
X_val   = df_val_s[final_numeric_cols].values

# y vectors (already encoded earlier using LabelEncoder)
# But if reset is needed, we redo encoding safely here:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(df_train_s["class"])
y_test  = le.transform(df_test_s["class"])
y_val   = le.transform(df_val_s["class"])

print("Classes:", le.classes_)
print("Encoded as:", list(le.transform(le.classes_)))

print("\nShapes:")
print("X_train:", X_train.shape, " y_train:", y_train.shape)
print("X_test :", X_test.shape,  " y_test :", y_test.shape)
print("X_val  :", X_val.shape,   " y_val  :", y_val.shape)


Classes: ['Benign' 'C&C' 'Scan']
Encoded as: [np.int64(0), np.int64(1), np.int64(2)]

Shapes:
X_train: (200000, 46)  y_train: (200000,)
X_test : (50000, 46)  y_test : (50000,)
X_val  : (50000, 46)  y_val  : (50000,)


In [6]:
# ============================================
# CELL 6 — Scale features (RAM-safe)
# ============================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit on train only (IMPORTANT)
X_train_scaled = scaler.fit_transform(X_train)

# Transform test + val
X_test_scaled  = scaler.transform(X_test)
X_val_scaled   = scaler.transform(X_val)

print("Scaling complete.")
print("Scaled shapes:")
print("Train:", X_train_scaled.shape)
print("Test :", X_test_scaled.shape)
print("Val  :", X_val_scaled.shape)


Scaling complete.
Scaled shapes:
Train: (200000, 46)
Test : (50000, 46)
Val  : (50000, 46)


In [7]:
# ============================================
# CELL 7 — XGBoost Multiclass Classifier
# ============================================

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

xgb_model = xgb.XGBClassifier(
    objective="multi:softprob",
    eval_metric="mlogloss",
    num_class=3,
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",   # fast + low memory
    random_state=42
)

print("Training XGBoost...")
xgb_model.fit(X_train_scaled, y_train)

print("\nPredicting on test set...")
xgb_pred = xgb_model.predict(X_test_scaled)

print("\nXGBoost Classification Report:")
print(classification_report(y_test, xgb_pred, target_names=le.classes_))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))

print("\nAccuracy:", accuracy_score(y_test, xgb_pred))


Training XGBoost...

Predicting on test set...

XGBoost Classification Report:
              precision    recall  f1-score   support

      Benign       0.90      0.94      0.92      1177
         C&C       1.00      1.00      1.00     48449
        Scan       0.85      0.76      0.80       374

    accuracy                           0.99     50000
   macro avg       0.91      0.90      0.91     50000
weighted avg       0.99      0.99      0.99     50000


Confusion Matrix:
[[ 1111    39    27]
 [   77 48347    25]
 [   50    40   284]]

Accuracy: 0.99484


In [11]:
# ============================================
# CELL 8 (FIXED) — DNN with CLASS WEIGHTS
# ============================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Compute class weights from TRAIN sample
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {i : class_weights[i] for i in range(3)}
print("Class Weights:", class_weight_dict)

# One-hot encode labels
y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test_cat  = tf.keras.utils.to_categorical(y_test, num_classes=3)

# Build DNN model
dnn_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

dnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Early stopping
es = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

print("Training DNN with Class Weights...")
history = dnn_model.fit(
    X_train_scaled, y_train_cat,
    validation_split=0.1,
    epochs=20,
    batch_size=2048,
    class_weight=class_weight_dict,
    callbacks=[es],
    verbose=1
)

print("Predicting on test set...")
dnn_pred_probs = dnn_model.predict(X_test_scaled)
dnn_pred = dnn_pred_probs.argmax(axis=1)

print("\nDNN (Weighted) Classification Report:")
print(classification_report(y_test, dnn_pred, target_names=le.classes_))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dnn_pred))

print("\nAccuracy:", accuracy_score(y_test, dnn_pred))


Class Weights: {0: np.float64(14.133276800226133), 1: np.float64(0.344055833380641), 2: np.float64(43.97537379067722)}
Training DNN with Class Weights...
Epoch 1/20


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


88/88 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - accuracy: 0.5548 - loss: 0.3230 - val_accuracy: 0.6884 - val_loss: 3.0354
Epoch 2/20
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.6884 - val_loss: 4.0376
Epoch 3/20
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.6884 - val_loss: 4.5994
Epoch 4/20
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 1.0000 - loss: 4.3863e-04 - val_accuracy: 0.6884 - val_loss: 5.0095
Predicting on test set...
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

DNN (Weighted) Classification Report:
              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      1177
         C&C       0.97      1.00      0.98     48449
        Scan       0.00      0.00      0.00       374

    accuracy                           0.97     50000
   macro avg       0.32      0.33      0.33     50000
weighted avg       0.94      0.97      0.95     50000


Confusion Ma

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [10]:
# ============================================
# FIXED CELL — BALANCE TRAINING DATA FOR DNN
# ============================================

df_train_bal = pd.concat([
    df_train_s[df_train_s["class"] == "Benign"],
    df_train_s[df_train_s["class"] == "Scan"],
    df_train_s[df_train_s["class"] == "C&C"].sample(n=7000, random_state=42)
], ignore_index=True)

print("Balanced Train Shape:", df_train_bal.shape)
print(df_train_bal["class"].value_counts())

# Build X_bal and y_bal
X_bal = df_train_bal[final_numeric_cols].values
y_bal = le.transform(df_train_bal["class"])

print("\nShapes after balancing:")
print("X_bal:", X_bal.shape)
print("y_bal:", y_bal.shape)


Balanced Train Shape: (13233, 48)
class
C&C       7000
Benign    4717
Scan      1516
Name: count, dtype: int64

Shapes after balancing:
X_bal: (13233, 46)
y_bal: (13233,)


In [12]:
# ============================================
# BALANCED DNN TRAINING
# ============================================

from tensorflow.keras.utils import to_categorical

y_bal_cat = to_categorical(y_bal, num_classes=3)

dnn2 = Sequential([
    Dense(128, activation='relu', input_shape=(X_bal.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

dnn2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("Training balanced DNN...")
dnn2.fit(X_bal, y_bal_cat, epochs=15, batch_size=256, validation_split=0.1, verbose=1)

print("Predicting...")
pred_bal = dnn2.predict(X_test_scaled).argmax(axis=1)

print("\nBalanced DNN Classification Report:")
print(classification_report(y_test, pred_bal, target_names=le.classes_))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, pred_bal))


Training balanced DNN...
Epoch 1/15


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


47/47 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step - accuracy: 0.4600 - loss: 2962877.0000 - val_accuracy: 0.0000e+00 - val_loss: 755441.0625
Epoch 2/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4763 - loss: 508173.4688 - val_accuracy: 0.9947 - val_loss: 65.0891
Epoch 3/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4655 - loss: 212881.8750 - val_accuracy: 0.9955 - val_loss: 10.3051
Epoch 4/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5092 - loss: 72748.5078 - val_accuracy: 0.9970 - val_loss: 3.3923
Epoch 5/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5297 - loss: 32789.6602 - val_accuracy: 0.9992 - val_loss: 2.7212
Epoch 6/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5182 - loss: 16530.8848 - val_accuracy: 0.9992 - val_loss: 1.9899
Epoch 7/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4974 - loss: 10128.0381 - val_accuracy: 0.9992 - val_loss: 1.4426
Epoch 8/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4963 - loss: 9102.457

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
# ============================================
# CELL 9 — Auto-balanced TEST set
# ============================================

# Find the smallest class count
min_count = min(
    len(df_test_s[df_test_s["class"] == "Benign"]),
    len(df_test_s[df_test_s["class"] == "Scan"]),
    len(df_test_s[df_test_s["class"] == "C&C"])
)

print("Minimum available samples per class:", min_count)

df_test_bal = pd.concat([
    df_test_s[df_test_s["class"] == "Benign"].sample(n=min_count, random_state=42),
    df_test_s[df_test_s["class"] == "Scan"].sample(n=min_count, random_state=42),
    df_test_s[df_test_s["class"] == "C&C"].sample(n=min_count, random_state=42)
], ignore_index=True)

print("\nBalanced Test Shape:", df_test_bal.shape)
print(df_test_bal["class"].value_counts())

# Build test matrices
X_test_bal = df_test_bal[final_numeric_cols].values
y_test_bal = le.transform(df_test_bal["class"])


Minimum available samples per class: 374

Balanced Test Shape: (1122, 48)
class
Benign    374
Scan      374
C&C       374
Name: count, dtype: int64


In [16]:
# ============================================
# CELL 10 — Evaluate DNN on balanced test
# ============================================

pred_bal = dnn2.predict(X_test_bal).argmax(axis=1)

print("\nBalanced DNN Classification Report:")
print(classification_report(y_test_bal, pred_bal, target_names=le.classes_))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_bal, pred_bal))


36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step

Balanced DNN Classification Report:
              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00       374
         C&C       0.34      1.00      0.51       374
        Scan       1.00      0.08      0.15       374

    accuracy                           0.36      1122
   macro avg       0.45      0.36      0.22      1122
weighted avg       0.45      0.36      0.22      1122


Confusion Matrix:
[[  0 374   0]
 [  0 374   0]
 [  5 339  30]]


In [17]:
# ============================================
# CELL A — SCALE BALANCED TRAIN & BALANCED TEST
# ============================================

# Scale balanced training set
X_bal_scaled = scaler.transform(X_bal)

# Scale balanced test set
X_test_bal_scaled = scaler.transform(X_test_bal)

print("Scaled balanced train:", X_bal_scaled.shape)
print("Scaled balanced test :", X_test_bal_scaled.shape)


Scaled balanced train: (13233, 46)
Scaled balanced test : (1122, 46)


In [18]:
# ============================================
# CELL B — TRAIN DNN ON SCALED BALANCED DATA
# ============================================

from tensorflow.keras.utils import to_categorical

y_bal_cat = to_categorical(y_bal, num_classes=3)

dnn3 = Sequential([
    Dense(128, activation='relu', input_shape=(X_bal_scaled.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

dnn3.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("Training corrected DNN...")
dnn3.fit(X_bal_scaled, y_bal_cat, epochs=15, batch_size=256, validation_split=0.1, verbose=1)

print("Predicting...")
pred_bal_corrected = dnn3.predict(X_test_bal_scaled).argmax(axis=1)

print("\nCorrected Balanced DNN Classification Report:")
print(classification_report(y_test_bal, pred_bal_corrected, target_names=le.classes_))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_bal, pred_bal_corrected))


Training corrected DNN...
Epoch 1/15


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


47/47 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - accuracy: 0.6388 - loss: 0.8500 - val_accuracy: 0.9713 - val_loss: 0.2036
Epoch 2/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8712 - loss: 0.3869 - val_accuracy: 0.9834 - val_loss: 0.1044
Epoch 3/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8970 - loss: 0.2902 - val_accuracy: 0.9834 - val_loss: 0.1007
Epoch 4/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9018 - loss: 0.2723 - val_accuracy: 0.9826 - val_loss: 0.0948
Epoch 5/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9112 - loss: 0.2461 - val_accuracy: 0.9834 - val_loss: 0.0954
Epoch 6/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9171 - loss: 0.2349 - val_accuracy: 0.9834 - val_loss: 0.0951
Epoch 7/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9227 - loss: 0.2244 - val_accuracy: 0.9841 - val_loss: 0.0953
Epoch 8/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9273 - loss: 0.2131 - val_accuracy: 0.9841 - val_loss: 0.0879
Ep

In [21]:
# ============================================
# FIXED CELL 9 — Prepare balanced datasets for experts
# ============================================

import numpy as np
from collections import Counter

def make_balanced_binary(df_source, pos_label, n_pos=None, n_neg=None, random_state=42):
    pos_df = df_source[df_source["class"] == pos_label]
    neg_df = df_source[df_source["class"] != pos_label]

    # Auto-adjust n_pos and n_neg
    if n_pos is None:
        n_pos = len(pos_df)
    n_pos = min(n_pos, len(pos_df))  # cannot exceed available

    if n_neg is None:
        n_neg = int(1.5 * n_pos)
    n_neg = min(n_neg, len(neg_df))  # cannot exceed available

    pos_sample = pos_df.sample(n=n_pos, random_state=random_state)
    neg_sample = neg_df.sample(n=n_neg, random_state=random_state)

    out = pd.concat([pos_sample, neg_sample], ignore_index=True)
    out = out.sample(frac=1, random_state=random_state).reset_index(drop=True)
    return out

# Training counts
counts = df_train_s["class"].value_counts().to_dict()
print("Train class counts:", counts)

n_benign = counts.get("Benign", 0)
n_scan   = counts.get("Scan", 0)
n_cnc    = min(7000, counts.get("C&C", 0))

print("\nUsing POS sizes:")
print("Benign =", n_benign)
print("Scan   =", n_scan)
print("C&C    =", n_cnc)

# TRAIN balanced sets
train_benign = make_balanced_binary(df_train_s, "Benign", n_pos=n_benign, n_neg=int(1.2*n_benign))
train_scan   = make_balanced_binary(df_train_s, "Scan",   n_pos=n_scan,   n_neg=int(1.2*n_scan))
train_cnc    = make_balanced_binary(df_train_s, "C&C",    n_pos=n_cnc,    n_neg=None) # auto-adjust

# VAL balanced sets
val_benign = make_balanced_binary(df_val_s, "Benign", n_pos=min(n_benign, len(df_val_s[df_val_s["class"]=="Benign"])))
val_scan   = make_balanced_binary(df_val_s, "Scan",   n_pos=min(n_scan, len(df_val_s[df_val_s["class"]=="Scan"])))
val_cnc    = make_balanced_binary(df_val_s, "C&C",    n_pos=min(n_cnc, len(df_val_s[df_val_s["class"]=="C&C"])))

# TEST balanced sets
test_benign = make_balanced_binary(df_test_s, "Benign", n_pos=min(n_benign, len(df_test_s[df_test_s["class"]=="Benign"])))
test_scan   = make_balanced_binary(df_test_s, "Scan",   n_pos=min(n_scan, len(df_test_s[df_test_s["class"]=="Scan"])))
test_cnc    = make_balanced_binary(df_test_s, "C&C",    n_pos=min(n_cnc, len(df_test_s[df_test_s["class"]=="C&C"])))

print("\n=== TRAIN SIZES ===")
print("Benign train:", train_benign.shape, Counter(train_benign["class"]))
print("Scan   train:", train_scan.shape,   Counter(train_scan["class"]))
print("C&C    train:", train_cnc.shape,    Counter(train_cnc["class"]))

print("\n=== VAL SIZES ===")
print("Benign val:", val_benign.shape, Counter(val_benign["class"]))
print("Scan   val:", val_scan.shape,   Counter(val_scan["class"]))
print("C&C    val:", val_cnc.shape,    Counter(val_cnc["class"]))

print("\n=== TEST SIZES ===")
print("Benign test:", test_benign.shape, Counter(test_benign["class"]))
print("Scan   test:", test_scan.shape,   Counter(test_scan["class"]))
print("C&C    test:", test_cnc.shape,    Counter(test_cnc["class"]))


Train class counts: {'C&C': 193767, 'Benign': 4717, 'Scan': 1516}

Using POS sizes:
Benign = 4717
Scan   = 1516
C&C    = 7000

=== TRAIN SIZES ===
Benign train: (10377, 48) Counter({'C&C': 5615, 'Benign': 4717, 'Scan': 45})
Scan   train: (3335, 48) Counter({'C&C': 1773, 'Scan': 1516, 'Benign': 46})
C&C    train: (13233, 48) Counter({'C&C': 7000, 'Benign': 4717, 'Scan': 1516})

=== VAL SIZES ===
Benign val: (2922, 48) Counter({'C&C': 1737, 'Benign': 1169, 'Scan': 16})
Scan   val: (957, 48) Counter({'C&C': 559, 'Scan': 383, 'Benign': 15})
C&C    val: (8552, 48) Counter({'C&C': 7000, 'Benign': 1169, 'Scan': 383})

=== TEST SIZES ===
Benign test: (2942, 48) Counter({'C&C': 1756, 'Benign': 1177, 'Scan': 9})
Scan   test: (935, 48) Counter({'C&C': 546, 'Scan': 374, 'Benign': 15})
C&C    test: (8551, 48) Counter({'C&C': 7000, 'Benign': 1177, 'Scan': 374})


In [22]:
# ============================================
# CELL 10 — Expert Model Builder Function
# ============================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.utils.class_weight import compute_class_weight

def build_expert_model():
    model = Sequential([
        Dense(64, activation='relu', input_shape=(len(final_numeric_cols),)),
        Dropout(0.3),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(2, activation='softmax')   # binary classification
    ])
    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model


In [23]:
# ============================================
# CELL 11 — Train Expert 1 (Benign Expert)
# ============================================

# Prepare training data
X_ben_train = scaler.transform(train_benign[final_numeric_cols])
y_ben_train = (train_benign["class"] == "Benign").astype(int)  # 1 = Benign, 0 = Other
y_ben_train_cat = to_categorical(y_ben_train, num_classes=2)

# Validation
X_ben_val = scaler.transform(val_benign[final_numeric_cols])
y_ben_val = (val_benign["class"] == "Benign").astype(int)
y_ben_val_cat = to_categorical(y_ben_val, num_classes=2)

# Build model
expert_benign = build_expert_model()

# Train
print("Training Benign Expert...")
expert_benign.fit(
    X_ben_train, y_ben_train_cat,
    validation_data=(X_ben_val, y_ben_val_cat),
    epochs=10,
    batch_size=256,
    verbose=1
)

# Evaluate on test set
X_ben_test = scaler.transform(test_benign[final_numeric_cols])
y_ben_test = (test_benign["class"] == "Benign").astype(int)

pred_ben = expert_benign.predict(X_ben_test).argmax(axis=1)

print("\n=== Benign Expert Report ===")
print(classification_report(y_ben_test, pred_ben))
print(confusion_matrix(y_ben_test, pred_ben))


Training Benign Expert...
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 64ms/step - accuracy: 0.6361 - loss: 0.6117 - val_accuracy: 0.9613 - val_loss: 0.3270
Epoch 2/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9561 - loss: 0.3080 - val_accuracy: 0.9757 - val_loss: 0.1377
Epoch 3/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9753 - loss: 0.1489 - val_accuracy: 0.9873 - val_loss: 0.0715
Epoch 4/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9821 - loss: 0.0972 - val_accuracy: 0.9877 - val_loss: 0.0585
Epoch 5/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9849 - loss: 0.0851 - val_accuracy: 0.9880 - val_loss: 0.0512
Epoch 6/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9823 - loss: 0.0775 - val_accuracy: 0.9877 - val_loss: 0.0464
Epoch 7/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9844 - loss: 0.0683 - val_accuracy: 0.9884 - val_loss: 0.0439
Epoch 8/10
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9866 - loss: 0.0594 - val_accuracy: 0.9890 - val_loss: 0.0411
Ep

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


92/92 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

=== Benign Expert Report ===
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      1765
           1       0.97      1.00      0.99      1177

    accuracy                           0.99      2942
   macro avg       0.99      0.99      0.99      2942
weighted avg       0.99      0.99      0.99      2942

[[1734   31]
 [   0 1177]]


In [24]:
# ============================================
# CELL 12 — Train Expert 2 (Scan Expert)
# ============================================

# Prepare training data
X_scan_train = scaler.transform(train_scan[final_numeric_cols])
y_scan_train = (train_scan["class"] == "Scan").astype(int)
y_scan_train_cat = to_categorical(y_scan_train, num_classes=2)

# Validation
X_scan_val = scaler.transform(val_scan[final_numeric_cols])
y_scan_val = (val_scan["class"] == "Scan").astype(int)
y_scan_val_cat = to_categorical(y_scan_val, num_classes=2)

# Build model
expert_scan = build_expert_model()

print("Training Scan Expert...")
expert_scan.fit(
    X_scan_train, y_scan_train_cat,
    validation_data=(X_scan_val, y_scan_val_cat),
    epochs=12,
    batch_size=256,
    verbose=1
)

# Evaluate on test set
X_scan_test = scaler.transform(test_scan[final_numeric_cols])
y_scan_test = (test_scan["class"] == "Scan").astype(int)

pred_scan = expert_scan.predict(X_scan_test).argmax(axis=1)

print("\n=== Scan Expert Report ===")
print(classification_report(y_scan_test, pred_scan))
print(confusion_matrix(y_scan_test, pred_scan))


Training Scan Expert...
Epoch 1/12


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


14/14 ━━━━━━━━━━━━━━━━━━━━ 10s 381ms/step - accuracy: 0.5608 - loss: 0.6926 - val_accuracy: 0.8955 - val_loss: 0.5596
Epoch 2/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8179 - loss: 0.5296 - val_accuracy: 0.9404 - val_loss: 0.4682
Epoch 3/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9217 - loss: 0.4523 - val_accuracy: 0.9530 - val_loss: 0.3762
Epoch 4/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9464 - loss: 0.3656 - val_accuracy: 0.9634 - val_loss: 0.2925
Epoch 5/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9619 - loss: 0.2830 - val_accuracy: 0.9697 - val_loss: 0.2231
Epoch 6/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9626 - loss: 0.2380 - val_accuracy: 0.9707 - val_loss: 0.1784
Epoch 7/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9631 - loss: 0.2142 - val_accuracy: 0.9707 - val_loss: 0.1602
Epoch 8/12
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9695 - loss: 0.1603 - val_accuracy: 0.9718 - val_loss: 0.1419


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

=== Scan Expert Report ===
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       561
           1       0.94      1.00      0.97       374

    accuracy                           0.97       935
   macro avg       0.97      0.98      0.97       935
weighted avg       0.98      0.97      0.97       935

[[537  24]
 [  0 374]]


In [26]:
# ============================================
# CELL 13 — Train Expert 3 (C&C Expert)
# ============================================

# Prepare training data
X_cnc_train = scaler.transform(train_cnc[final_numeric_cols])
y_cnc_train = (train_cnc["class"] == "C&C").astype(int)
y_cnc_train_cat = to_categorical(y_cnc_train, num_classes=2)

# Validation
X_cnc_val = scaler.transform(val_cnc[final_numeric_cols])
y_cnc_val = (val_cnc["class"] == "C&C").astype(int)
y_cnc_val_cat = to_categorical(y_cnc_val, num_classes=2)

# Build model
expert_cnc = build_expert_model()

print("Training C&C Expert...")
expert_cnc.fit(
    X_cnc_train, y_cnc_train_cat,
    validation_data=(X_cnc_val, y_cnc_val_cat),
    epochs=12,
    batch_size=256,
    verbose=1
)

# Evaluate on test set
X_cnc_test = scaler.transform(test_cnc[final_numeric_cols])
y_cnc_test = (test_cnc["class"] == "C&C").astype(int)

pred_cnc = expert_cnc.predict(X_cnc_test).argmax(axis=1)

print("\n=== C&C Expert Report ===")
print(classification_report(y_cnc_test, pred_cnc))
print(confusion_matrix(y_cnc_test, pred_cnc))


Training C&C Expert...
Epoch 1/12


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


52/52 ━━━━━━━━━━━━━━━━━━━━ 7s 69ms/step - accuracy: 0.7227 - loss: 0.7183 - val_accuracy: 0.9647 - val_loss: 0.2906
Epoch 2/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9664 - loss: 0.2290 - val_accuracy: 0.9676 - val_loss: 0.1146
Epoch 3/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9785 - loss: 0.1060 - val_accuracy: 0.9854 - val_loss: 0.0825
Epoch 4/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9844 - loss: 0.0787 - val_accuracy: 0.9866 - val_loss: 0.0688
Epoch 5/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9867 - loss: 0.0720 - val_accuracy: 0.9868 - val_loss: 0.0660
Epoch 6/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9890 - loss: 0.0686 - val_accuracy: 0.9871 - val_loss: 0.0639
Epoch 7/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9903 - loss: 0.0522 - val_accuracy: 0.9876 - val_loss: 0.0606
Epoch 8/12
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9898 - loss: 0.0588 - val_accuracy: 0.9876 - val_loss: 0.0590
Ep

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

=== C&C Expert Report ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1551
           1       1.00      0.98      0.99      7000

    accuracy                           0.99      8551
   macro avg       0.96      0.99      0.98      8551
weighted avg       0.99      0.99      0.99      8551

[[1551    0]
 [ 127 6873]]


In [27]:
# ============================================
# CELL A — Build meta training/test features from expert probs
# ============================================

import numpy as np
from sklearn.preprocessing import LabelEncoder

# helper to compute expert positive-class prob for a dataframe
def expert_probs_for_df(df):
    X = scaler.transform(df[final_numeric_cols])
    p_ben = expert_benign.predict(X)[:,1]   # P(Benign)
    p_cnc  = expert_cnc.predict(X)[:,1]    # P(C&C)
    p_scan = expert_scan.predict(X)[:,1]   # P(Scan)
    # Stack as columns in order [p_ben, p_cnc, p_scan] mapped to class indices [0,1,2]
    return np.vstack([p_ben, p_cnc, p_scan]).T

# Build meta-training set from validation balanced parts: concatenate val_benign, val_scan, val_cnc
meta_train_df = pd.concat([val_benign, val_scan, val_cnc], ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
meta_X_train_expert = expert_probs_for_df(meta_train_df)  # shape (N_meta_train, 3)
meta_X_train_feat   = scaler.transform(meta_train_df[final_numeric_cols])  # feature inputs (for AMNN gating)
meta_y_train        = le.transform(meta_train_df["class"])  # 0,1,2

print("Meta-train size:", meta_X_train_expert.shape)
print("Meta-train class counts:", np.bincount(meta_y_train))

# Prepare balanced test (we created df_test_bal earlier)
meta_test_bal_df = df_test_bal.copy().reset_index(drop=True)
meta_X_test_bal_expert = expert_probs_for_df(meta_test_bal_df)
meta_X_test_bal_feat   = scaler.transform(meta_test_bal_df[final_numeric_cols])
meta_y_test_bal = le.transform(meta_test_bal_df["class"])

print("Meta-test (balanced) size:", meta_X_test_bal_expert.shape)
print("Balanced test class counts:", np.bincount(meta_y_test_bal))

# Prepare full sampled test for real-world evaluation (df_test_s)
meta_test_full_df = df_test_s.copy().reset_index(drop=True)
meta_X_test_full_expert = expert_probs_for_df(meta_test_full_df)
meta_X_test_full_feat   = scaler.transform(meta_test_full_df[final_numeric_cols])
meta_y_test_full = le.transform(meta_test_full_df["class"])

print("Meta-test (full) size:", meta_X_test_full_expert.shape)
print("Full test class counts:", np.bincount(meta_y_test_full))

# Save quick copies
np.save("/content/meta_X_train_expert.npy", meta_X_train_expert)
np.save("/content/meta_X_test_bal_expert.npy", meta_X_test_bal_expert)
np.save("/content/meta_X_test_full_expert.npy", meta_X_test_full_expert)
np.save("/content/meta_y_train.npy", meta_y_train)
np.save("/content/meta_y_test_bal.npy", meta_y_test_bal)
np.save("/content/meta_y_test_full.npy", meta_y_test_full)

print("Saved meta arrays to /content/")


 27/389 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step  

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


389/389 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step
389/389 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
389/389 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Meta-train size: (12431, 3)
Meta-train class counts: [2353 9296  782]
 1/36 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Meta-test (balanced) size: (1122, 3)
Balanced test class counts: [374 374 374]
   1/1563 ━━━━━━━━━━━━━━━━━━━━ 43s 28ms/step

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


1563/1563 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
Meta-test (full) size: (50000, 3)
Full test class counts: [ 1177 48449   374]
Saved meta arrays to /content/


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [28]:
# ============================================
# CELL B — Train LR and XGBoost meta-classifiers
# ============================================

from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Use meta features (expert probs) as input for meta-classifiers
X_meta_train = meta_X_train_expert
y_meta_train = meta_y_train

X_meta_test_bal = meta_X_test_bal_expert
y_meta_test_bal = meta_y_test_bal

X_meta_test_full = meta_X_test_full_expert
y_meta_test_full = meta_y_test_full

# Logistic Regression (multinomial)
lr = LogisticRegression(multi_class='multinomial', max_iter=2000)
lr.fit(X_meta_train, y_meta_train)

# Evaluate on balanced test
lr_pred_bal = lr.predict(X_meta_test_bal)
print("\n=== LR on BALANCED test ===")
print("Accuracy:", accuracy_score(y_meta_test_bal, lr_pred_bal))
print(classification_report(y_meta_test_bal, lr_pred_bal, target_names=le.classes_))
print("Confusion matrix:\n", confusion_matrix(y_meta_test_bal, lr_pred_bal))

# Evaluate on full test
lr_pred_full = lr.predict(X_meta_test_full)
print("\n=== LR on FULL test ===")
print("Accuracy:", accuracy_score(y_meta_test_full, lr_pred_full))
print(classification_report(y_meta_test_full, lr_pred_full, target_names=le.classes_))
print("Confusion matrix:\n", confusion_matrix(y_meta_test_full, lr_pred_full))


# XGBoost meta-classifier (multiclass)
xgb_meta = xgb.XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    eval_metric="mlogloss",
    n_estimators=200,
    max_depth=4,
    learning_rate=0.1,
    use_label_encoder=False,
    tree_method="hist",
    random_state=42
)
xgb_meta.fit(X_meta_train, y_meta_train)

# Evaluate XGB on balanced test
xgb_pred_bal = xgb_meta.predict(X_meta_test_bal)
print("\n=== XGB meta on BALANCED test ===")
print("Accuracy:", accuracy_score(y_meta_test_bal, xgb_pred_bal))
print(classification_report(y_meta_test_bal, xgb_pred_bal, target_names=le.classes_))
print("Confusion matrix:\n", confusion_matrix(y_meta_test_bal, xgb_pred_bal))

# Evaluate XGB on full test
xgb_pred_full = xgb_meta.predict(X_meta_test_full)
print("\n=== XGB meta on FULL test ===")
print("Accuracy:", accuracy_score(y_meta_test_full, xgb_pred_full))
print(classification_report(y_meta_test_full, xgb_pred_full, target_names=le.classes_))
print("Confusion matrix:\n", confusion_matrix(y_meta_test_full, xgb_pred_full))


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(



=== LR on BALANCED test ===
Accuracy: 0.7388591800356507
              precision    recall  f1-score   support

      Benign       0.56      1.00      0.72       374
         C&C       1.00      0.98      0.99       374
        Scan       0.98      0.24      0.38       374

    accuracy                           0.74      1122
   macro avg       0.85      0.74      0.70      1122
weighted avg       0.85      0.74      0.70      1122

Confusion matrix:
 [[374   0   0]
 [  5 367   2]
 [285   1  88]]

=== LR on FULL test ===
Accuracy: 0.98024
              precision    recall  f1-score   support

      Benign       0.58      1.00      0.73      1177
         C&C       1.00      0.99      0.99     48449
        Scan       0.40      0.24      0.30       374

    accuracy                           0.98     50000
   macro avg       0.66      0.74      0.67     50000
weighted avg       0.99      0.98      0.98     50000

Confusion matrix:
 [[ 1177     0     0]
 [  571 47747   131]
 [  285    

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [18:19:03] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



=== XGB meta on BALANCED test ===
Accuracy: 0.8190730837789661
              precision    recall  f1-score   support

      Benign       0.67      0.96      0.79       374
         C&C       0.96      0.99      0.98       374
        Scan       0.94      0.51      0.66       374

    accuracy                           0.82      1122
   macro avg       0.86      0.82      0.81      1122
weighted avg       0.86      0.82      0.81      1122

Confusion matrix:
 [[360   3  11]
 [  2 370   2]
 [174  11 189]]

=== XGB meta on FULL test ===
Accuracy: 0.98436
              precision    recall  f1-score   support

      Benign       0.66      0.97      0.78      1177
         C&C       1.00      0.99      0.99     48449
        Scan       0.51      0.51      0.51       374

    accuracy                           0.98     50000
   macro avg       0.72      0.82      0.76     50000
weighted avg       0.99      0.98      0.99     50000

Confusion matrix:
 [[ 1136     7    34]
 [  410 47893   146]

In [29]:
# ============================================
# CELL C — Build & Train AMNN gating network
# ============================================

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Softmax, Lambda, Multiply
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
import tensorflow.keras.backend as K

# Meta train inputs
feat_in = meta_X_train_feat       # scaled features (N, D)
expert_in = meta_X_train_expert   # expert probs (N, 3)
y_meta_cat = to_categorical(meta_y_train, num_classes=3)

# Define model
input_feat = Input(shape=(feat_in.shape[1],), name="feat_in")
input_expert = Input(shape=(3,), name="expert_in")

x = Dense(32, activation='relu')(input_feat)
x = Dense(16, activation='relu')(x)
weights_out = Dense(3, activation='softmax', name="weights_out")(x)  # weights over experts

# elementwise multiply weights and expert probs -> [w0*p_ben, w1*p_cnc, w2*p_scan]
weighted = Multiply()([weights_out, input_expert])

# normalize to make a probability distribution across classes
def renorm(t):
    s = K.sum(t, axis=1, keepdims=True) + K.epsilon()
    return t / s

final_probs = Lambda(lambda z: renorm(z), name="final_probs")(weighted)

amnn = Model([input_feat, input_expert], final_probs)
amnn.compile(optimizer=Adam(learning_rate=1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

print("AMNN summary:")
amnn.summary()

# Train AMNN (validation-based meta train)
history = amnn.fit(
    [meta_X_train_feat, meta_X_train_expert], y_meta_cat,
    epochs=60,
    batch_size=128,
    validation_split=0.1,
    verbose=1
)

# Prepare balanced test inputs
X_feat_test_bal = meta_X_test_bal_feat
X_expert_test_bal = meta_X_test_bal_expert
y_test_bal_cat = to_categorical(meta_y_test_bal, num_classes=3)

# Evaluate on balanced test
amnn_pred_prob_bal = amnn.predict([X_feat_test_bal, X_expert_test_bal])
amnn_pred_bal = amnn_pred_prob_bal.argmax(axis=1)

print("\n=== AMNN on BALANCED test ===")
print("Accuracy:", (amnn_pred_bal == meta_y_test_bal).mean())
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(meta_y_test_bal, amnn_pred_bal, target_names=le.classes_))
print("Confusion:\n", confusion_matrix(meta_y_test_bal, amnn_pred_bal))

# Evaluate on full test
X_feat_test_full = meta_X_test_full_feat
X_expert_test_full = meta_X_test_full_expert

amnn_pred_prob_full = amnn.predict([X_feat_test_full, X_expert_test_full], batch_size=2048)
amnn_pred_full = amnn_pred_prob_full.argmax(axis=1)

print("\n=== AMNN on FULL test ===")
print("Accuracy:", (amnn_pred_full == meta_y_test_full).mean())
print(classification_report(meta_y_test_full, amnn_pred_full, target_names=le.classes_))
print("Confusion:\n", confusion_matrix(meta_y_test_full, amnn_pred_full))


AMNN summary:


Model: "functional_9"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ feat_in             │ (None, 46)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_32 (Dense)    │ (None, 32)        │      1,504 │ feat_in[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_33 (Dense)    │ (None, 16)        │        528 │ dense_32[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ weights_out (Dense) │ (None, 3)         │         51 │ dense_33[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expert_in           │ (None, 3)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multiply (Multiply) │ (None, 3)         │          0 │ weights_out[0][0… │
│                     │                   │            │ expert_in[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ final_probs         │ (None, 3)         │          0 │ multiply[0][0]    │
│ (Lambda)            │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 2,083 (8.14 KB)

 Trainable params: 2,083 (8.14 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - accuracy: 0.9328 - loss: 0.2041 - val_accuracy: 0.9510 - val_loss: 0.1561
Epoch 2/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9547 - loss: 0.1615 - val_accuracy: 0.9590 - val_loss: 0.1138
Epoch 3/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9588 - loss: 0.1326 - val_accuracy: 0.9590 - val_loss: 0.1046
Epoch 4/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9632 - loss: 0.1115 - val_accuracy: 0.9630 - val_loss: 0.1023
Epoch 5/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9602 - loss: 0.1157 - val_accuracy: 0.9646 - val_loss: 0.1067
Epoch 6/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9591 - loss: nan - val_accuracy: 0.0643 - val_loss: nan
Epoch 7/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0632 - loss: nan - val_accuracy: 0.0643 - val_loss: nan
Epoch 8/60
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0607 - loss: nan - val_accuracy: 0.0643 - val_loss: nan
Epoch 9/

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step

=== AMNN on FULL test ===
Accuracy: 0.02354
              precision    recall  f1-score   support

      Benign       0.02      1.00      0.05      1177
         C&C       0.00      0.00      0.00     48449
        Scan       0.00      0.00      0.00       374

    accuracy                           0.02     50000
   macro avg       0.01      0.33      0.02     50000
weighted avg       0.00      0.02      0.00     50000

Confusion:
 [[ 1177     0     0]
 [48449     0     0]
 [  374     0     0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [30]:
# ============================================
# CORRECTED AMNN — Expert-only gating network
# ============================================

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Multiply, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical
import tensorflow.keras.backend as K

# Use EXPERT PROBABILITIES ONLY (NOT features)
X_train_amnn = meta_X_train_expert          # (N,3)
y_train_amnn = to_categorical(meta_y_train) # (N,3)

X_test_bal_amnn  = meta_X_test_bal_expert
y_test_bal_amnn  = meta_y_test_bal

X_test_full_amnn = meta_X_test_full_expert
y_test_full_amnn = meta_y_test_full

# Define gating network
input_expert = Input(shape=(3,), name="expert_probs")

g = Dense(16, activation='relu')(input_expert)
g = Dense(3, activation='softmax', name="weights")(g)   # produce 3 weights (for 3 classes)

# Weighted combination: elementwise multiply
weighted = Multiply()([input_expert, g])

# Normalize probabilities
def renorm(t):
    s = K.sum(t, axis=1, keepdims=True) + 1e-8
    return t / s

final_out = Lambda(renorm, name="final_probs")(weighted)

amnn_fixed = Model(inputs=input_expert, outputs=final_out)
amnn_fixed.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print(amnn_fixed.summary())

# Train
history = amnn_fixed.fit(
    X_train_amnn, y_train_amnn,
    validation_split=0.1,
    epochs=40,
    batch_size=128,
    verbose=1
)

# Evaluate on balanced test
pred_bal = amnn_fixed.predict(X_test_bal_amnn).argmax(axis=1)
print("\n=== FIXED AMNN on BALANCED test ===")
print("Accuracy:", accuracy_score(y_test_bal_amnn, pred_bal))
print(classification_report(y_test_bal_amnn, pred_bal, target_names=le.classes_))
print("Confusion:\n", confusion_matrix(y_test_bal_amnn, pred_bal))

# Evaluate on full test
pred_full = amnn_fixed.predict(X_test_full_amnn).argmax(axis=1)
print("\n=== FIXED AMNN on FULL test ===")
print("Accuracy:", accuracy_score(y_test_full_amnn, pred_full))
print(classification_report(y_test_full_amnn, pred_full, target_names=le.classes_))
print("Confusion:\n", confusion_matrix(y_test_full_amnn, pred_full))


Model: "functional_10"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ expert_probs        │ (None, 3)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_34 (Dense)    │ (None, 16)        │         64 │ expert_probs[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ weights (Dense)     │ (None, 3)         │         51 │ dense_34[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multiply_1          │ (None, 3)         │          0 │ expert_probs[0][… │
│ (Multiply)          │                   │            │ weights[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ final_probs         │ (None, 3)         │          0 │ multiply_1[0][0]  │
│ (Lambda)            │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 115 (460.00 B)

 Trainable params: 115 (460.00 B)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - accuracy: 0.8300 - loss: 0.2976 - val_accuracy: 0.9341 - val_loss: 0.2533
Epoch 2/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9416 - loss: 0.2255 - val_accuracy: 0.9325 - val_loss: 0.2343
Epoch 3/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9377 - loss: 0.2056 - val_accuracy: 0.9325 - val_loss: 0.2206
Epoch 4/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9392 - loss: 0.1974 - val_accuracy: 0.9333 - val_loss: 0.2073
Epoch 5/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9395 - loss: 0.1806 - val_accuracy: 0.9333 - val_loss: 0.1953
Epoch 6/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9406 - loss: 0.1682 - val_accuracy: 0.9325 - val_loss: 0.1865
Epoch 7/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9375 - loss: 0.1764 - val_accuracy: 0.9317 - val_loss: 0.1820
Epoch 8/40
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9339 - loss: 0.1722 - val_accuracy: 0.9317 - val